# -----------------
# This is the build file ONLY for Production deployment
# WORKFLOW:
# -> Build Phase:
  # -> Install npm dependencies
  # -> Unit test react components with Jest
  # -> Build frontend with npm
  # -> Check GCP artifact registry for existing Docker images
  # -> Build Docker image if there isn't an existing one
  # -> Test container(backend) with pytest tests
  # -> Push image to artifact registry
# -> Deployment Phase
  # -> Deploy backend service to Cloud Run
  # -> Install jq. Use Bash to modify firebase.json to point to the production backend service
  # -> Deploy frontend to firebase without hosting channel setting
# -----------------

# TODO: Figure out how to deploy backend with no traffic and then shift traffic

steps:

# ----------------
# BUILD PHASE
# ----------------
- name: 'node'
  id: 'Install npm Dependencies'
  dir: 'frontend'
  entrypoint: 'npm'
  args: ['install']
  waitFor: ['-']

- name: 'node'
  id: 'Unit Test Frontend'
  dir: 'frontend'
  entrypoint: 'npm'
  args: ['test']
  waitFor: ['Install npm Dependencies']

- name: 'node'
  id: 'Build Frontend'
  dir: 'frontend'
  entrypoint: 'npm'
  args: ['run', 'build']
  waitFor: ['Unit Test Frontend']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Pull Cache'
  dir: 'backend'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/country-view:latest || exit 0']
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  dir: 'backend'
  args:
    - 'build'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/country-view:latest'
    - '-t'
    - 'gcr.io/$PROJECT_ID/country-view:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/country-view:latest'
    - '.'
  waitFor: ['Pull Cache']

- name: 'gcr.io/$PROJECT_ID/country-view:$COMMIT_SHA'
  id: 'Unit Test Backend'
  dir: 'backend'
  entrypoint: '/bin/sh'
  args: ['-c', 'pip install -r requirements-tests.txt && pytest']
  secretEnv: ['CONGRESS_API_KEY']
  waitFor: ['Build Image']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  dir: 'backend'
  args: ['push', 'gcr.io/$PROJECT_ID/country-view', '--all-tags']
  waitFor: ['Unit Test Backend', 'Unit Test Frontend']

# ---------------
# DEPLOYMENT PHASE
# ---------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  dir: 'backend'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'country-view', '--region', 'us-central1',
         '--image', 'gcr.io/$PROJECT_ID/country-view:$COMMIT_SHA',
         '--platform', 'managed',
         '--set-secrets=CONGRESS_API_KEY=CONGRESS_API_KEY:latest',
         '--cpu=2', '--memory=4Gi']
  waitFor: ['Push Image']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Modify firebase.json'
  dir: 'frontend'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y jq
      tmpfile=$(mktemp)
      cp firebase.json "$tmpfile"
      jq (.hosting.rewrites[0].run | select(.serviceId == "country-view-dev")).Value |= "county-view" "$tmpfile" >firebase.json
      rm -f -- "$tmpfile"
  waitFor: ['Push Image']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  id: 'Deploy to Firebase'
  dir: 'frontend'
  args: ['deploy', '--only', 'hosting']
  secretEnv: ['FIREBASE_API_KEY']
  waitFor: ['Modify firebase.json', 'Deploy to Cloud Run']

availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/CONGRESS_API_KEY/versions/latest'
    env: 'CONGRESS_API_KEY'
  - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest'
    env: 'FIREBASE_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
